services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-save-bot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
      - ./cookies.txt:/app/cookies.txt
